/**
 * Sp8de Game API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SignedItem } from './signedItem';


export interface GameStartResponse {
    gameId?: string;
    items?: Array<SignedItem>;
    bet?: Array<number>;
    betAmount?: number;
    gameType?: GameStartResponse.GameTypeEnum;
    validationTx?: string;
    ipfsHash?: string;
}
export namespace GameStartResponse {
    export type GameTypeEnum = 'TossCoin' | 'Dice' | 'NumberRange' | 'SingleZeroWheel' | 'DoubleZeroWheel';
    export const GameTypeEnum = {
        TossCoin: 'TossCoin' as GameTypeEnum,
        Dice: 'Dice' as GameTypeEnum,
        NumberRange: 'NumberRange' as GameTypeEnum,
        SingleZeroWheel: 'SingleZeroWheel' as GameTypeEnum,
        DoubleZeroWheel: 'DoubleZeroWheel' as GameTypeEnum
    }
}
