/**
 * Sp8de Game API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GameStartRequest {
    type?: GameStartRequest.TypeEnum;
    bet?: Array<number>;
    betAmount?: number;
    pubKey?: string;
    sign?: string;
    nonce?: number;
}
export namespace GameStartRequest {
    export type TypeEnum = 'TossCoin' | 'Dice' | 'NumberRange' | 'SingleZeroWheel' | 'DoubleZeroWheel';
    export const TypeEnum = {
        TossCoin: 'TossCoin' as TypeEnum,
        Dice: 'Dice' as TypeEnum,
        NumberRange: 'NumberRange' as TypeEnum,
        SingleZeroWheel: 'SingleZeroWheel' as TypeEnum,
        DoubleZeroWheel: 'DoubleZeroWheel' as TypeEnum
    }
}
