// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sp8de.Protocol.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SignedItem
    {
        /// <summary>
        /// Initializes a new instance of the SignedItem class.
        /// </summary>
        public SignedItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SignedItem class.
        /// </summary>
        /// <param name="type">Possible values include: 'Contributor',
        /// 'Requester', 'Validator'</param>
        public SignedItem(string type = default(string), string pubKey = default(string), string nonce = default(string), string sign = default(string), string seed = default(string))
        {
            Type = type;
            PubKey = pubKey;
            Nonce = nonce;
            Sign = sign;
            Seed = seed;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'Contributor', 'Requester',
        /// 'Validator'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pubKey")]
        public string PubKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nonce")]
        public string Nonce { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sign")]
        public string Sign { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "seed")]
        public string Seed { get; set; }

    }
}
