// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sp8de.Protocol.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TransactionData
    {
        /// <summary>
        /// Initializes a new instance of the TransactionData class.
        /// </summary>
        public TransactionData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TransactionData class.
        /// </summary>
        public TransactionData(IDictionary<string, IList<string>> items = default(IDictionary<string, IList<string>>), string hash = default(string))
        {
            Items = items;
            Hash = hash;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IDictionary<string, IList<string>> Items { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hash")]
        public string Hash { get; set; }

    }
}
