// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sp8de.Protocol.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TransactionMeta
    {
        /// <summary>
        /// Initializes a new instance of the TransactionMeta class.
        /// </summary>
        public TransactionMeta()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TransactionMeta class.
        /// </summary>
        public TransactionMeta(long? blockId = default(long?))
        {
            BlockId = blockId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "blockId")]
        public long? BlockId { get; set; }

    }
}
