/**
 * Sp8de Explorer API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Anchor } from './anchor';


export interface Sp8deBlock {
    id?: number;
    chainId?: number;
    hash?: string;
    previousHash?: string;
    transactionRoot?: string;
    signer?: string;
    signature?: string;
    timestamp?: number;
    transactionsCount?: number;
    transactions?: Array<string>;
    anchors?: Array<Anchor>;
}
